services:
  maggor:
    build: .
    container_name: maggor
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/maggor
    networks:
      - external
      - internal
  database:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=maggor
      - MONGO_INITDB_ROOT_PASSWORD=secure123
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./data/mongo:/data/db
    networks:
      - internal
networks:
  external:
  internal: